version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=django-insecure-ipsco-deploy-2025-08-17-secret-key-for-production-deployment
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=gestion_vehicules.settings
    volumes:
      - .:/app
    command: gunicorn gestion_vehicules.wsgi:application --bind 0.0.0.0:8000 --reload
  
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=ipsco
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: 