# Generated by Django 4.2.20 on 2025-05-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_etablissement_course_date_souhaitee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='nombre_passagers',
            field=models.PositiveIntegerField(default=1, verbose_name='Nombre de passagers'),
        ),
    ]
