# Generated by Django 4.2.20 on 2025-06-01 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_course_nombre_passagers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True, verbose_name='Application ouverte')),
                ('start_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Début d'utilisation autorisée")),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name="Fin d'utilisation autorisée")),
                ('message', models.TextField(blank=True, default="L'application est actuellement bloquée. Veuillez contacter l'administrateur.")),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueKilometrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('module', models.CharField(choices=[('course', 'Course'), ('ravitaillement', 'Ravitaillement'), ('entretien', 'Entretien')], max_length=20)),
                ('objet_id', models.PositiveIntegerField()),
                ('valeur_avant', models.PositiveIntegerField(blank=True, null=True)),
                ('valeur_apres', models.PositiveIntegerField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques_kilometrage', to='core.vehicule')),
            ],
        ),
    ]
