# Generated by Django 4.2.20 on 2025-06-09 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_applicationcontrol_historiquekilometrage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etablissement',
            options={'ordering': ['type', 'nom'], 'verbose_name': 'Département', 'verbose_name_plural': 'Départements'},
        ),
        migrations.AddField(
            model_name='etablissement',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='code',
            field=models.CharField(blank=True, help_text='Code unique du département', max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='date_modification',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='core.etablissement'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements_diriges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='type',
            field=models.CharField(choices=[('departement', 'Département'), ('direction', 'Direction'), ('service', 'Service')], default='departement', max_length=20),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='departements_accessibles',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs_autorises', to='core.etablissement'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_modification',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='date_modification',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
