# Generated by Django 4.2.20 on 2025-06-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_etablissement_date_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='kilometrage_actuel',
            field=models.PositiveIntegerField(blank=True, help_text='Kilométrage actuel du véhicule (centralisé)', null=True),
        ),
    ]
