# Generated by Django 4.2.20 on 2025-06-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_vehicule_kilometrage_actuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='priorite',
            field=models.CharField(choices=[('important', 'Important'), ('urgence', 'Urgence'), ('haute_urgence', 'Haute urgence')], default='important', max_length=20, verbose_name='Priorité'),
        ),
    ]
