# Generated by Django 4.2.20 on 2025-06-22 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_system_message',
            field=models.BooleanField(default=False, help_text='Indique si le message est un message système (non lié à un utilisateur spécifique)'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL),
        ),
    ]
