# Generated by Django 4.2.20 on 2025-07-09 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_message_is_system_message_alter_message_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueCorrectionKilometrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_correction', models.DateTimeField(auto_now_add=True)),
                ('valeur_avant', models.PositiveIntegerField()),
                ('valeur_apres', models.PositiveIntegerField()),
                ('motif', models.TextField(blank=True, null=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections_kilometrage_auteur', to=settings.AUTH_USER_MODEL)),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections_kilometrage', to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections_kilometrage', to='core.vehicule')),
            ],
        ),
    ]
