name: demandeur_app
description: Application mobile pour les demandeurs de courses IPS-CO
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Navigation
  go_router: ^13.2.5
  
  # Gestion d'état
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  
  # HTTP et API
  dio: ^5.9.0
  retrofit: ^4.7.1
  http: ^1.5.0
  
  # Stockage local
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  
  # Authentification
  local_auth: ^2.3.0
  
  # Notifications
  firebase_core: ^2.32.0
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.3
  
  # Géolocalisation et cartes
  geolocator: ^10.1.1
  geocoding: ^2.2.2
  
  # UI et animations
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  lottie: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  
  # Utilitaires
  intl: ^0.19.0
  url_launcher: ^6.3.2
  image_picker: ^1.1.2
  permission_handler: ^11.4.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code generation
  build_runner: ^2.5.4
  riverpod_generator: ^2.6.1
  retrofit_generator: ^8.2.1
  json_serializable: ^6.9.0
  hive_generator: ^2.0.1
  
  # Linting
  flutter_lints: ^3.0.2
  custom_lint: ^0.6.10
  riverpod_lint: ^2.6.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
