# Generated by Django 4.2.10 on 2025-05-10 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('type_rapport', models.CharField(choices=[('course', 'Rapport de courses'), ('vehicule', 'Rapport de véhicule'), ('chauffeur', 'Rapport de chauffeur'), ('entretien', "Rapport d'entretien"), ('ravitaillement', 'Rapport de ravitaillement'), ('general', 'Rapport général')], max_length=20)),
                ('format_rapport', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='rapports/')),
                ('parametres', models.JSONField(blank=True, null=True)),
                ('generateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_generes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
