# Generated by Django 4.2.20 on 2025-05-30 12:08

from django.db import migrations, models
import entretien.models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entretien',
            name='kilometrage',
            field=models.PositiveIntegerField(default=0, help_text="Kilométrage du véhicule au moment de l'entretien"),
        ),
        migrations.AddField(
            model_name='entretien',
            name='kilometrage_apres',
            field=models.PositiveIntegerField(default=0, help_text="Kilométrage du véhicule après l'entretien", verbose_name='Kilométrage après entretien'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='piece_justificative',
            field=models.FileField(blank=True, help_text='Facture, reçu ou autre document justificatif (PDF, JPG, PNG)', null=True, upload_to=entretien.models.piece_justificative_path),
        ),
        migrations.AddField(
            model_name='entretien',
            name='type_entretien',
            field=models.CharField(choices=[('ordinaire', 'Entretien ordinaire'), ('mecanique', 'Entretien mécanique')], default='ordinaire', max_length=20, verbose_name="Type d'entretien"),
        ),
    ]
