# Generated by Django 4.2.10 on 2025-05-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceJournaliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('distance_totale', models.PositiveIntegerField(default=0)),
                ('nombre_courses', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueChauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=50)),
                ('kilometrage', models.PositiveIntegerField()),
                ('commentaire', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
