# Generated by Django 4.2.10 on 2025-05-10 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chauffeur', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquechauffeur',
            name='chauffeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_chauffeur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiquechauffeur',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_chauffeur', to='core.course'),
        ),
        migrations.AddField(
            model_name='historiquechauffeur',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_chauffeur', to='core.vehicule'),
        ),
        migrations.AddField(
            model_name='distancejournaliere',
            name='chauffeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances_journalieres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='distancejournaliere',
            unique_together={('chauffeur', 'date')},
        ),
    ]
