# Generated by Django 4.2.20 on 2025-07-11 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chauffeur', '0003_commentairerapportchauffeur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distancejournaliere',
            options={'verbose_name': 'Distance journalière', 'verbose_name_plural': 'Distances journalières'},
        ),
        migrations.CreateModel(
            name='CommentaireRapportDemandeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('texte', models.TextField()),
                ('date_commentaire', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commentaires_ecrits_demandeur', to=settings.AUTH_USER_MODEL)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_rapport_demandeur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
