# Generated by Django 4.2.10 on 2025-05-10 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=50)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('chauffeur_assigne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_assignations', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_dispatch', to='core.course')),
                ('dispatcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_dispatch', to=settings.AUTH_USER_MODEL)),
                ('vehicule_assigne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_assignations', to='core.vehicule')),
            ],
        ),
    ]
