# Generated by Django 4.2.20 on 2025-06-02 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_applicationcontrol_historiquekilometrage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentSecurite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_signalement', models.DateTimeField(default=django.utils.timezone.now)),
                ('type_incident', models.CharField(choices=[('panne', 'Panne'), ('accident', 'Accident'), ('defaut_grave', 'Défaut grave'), ('autre', 'Autre')], default='autre', max_length=50)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='incidents_securite/')),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('traite', 'Traité'), ('clos', 'Clos')], default='ouvert', max_length=20)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents_signales', to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents_securite', to='core.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='CheckListSecurite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_controle', models.DateTimeField(default=django.utils.timezone.now)),
                ('lieu_controle', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('conforme', 'Conforme'), ('anomalie_mineure', 'Anomalie mineure'), ('non_conforme', 'Non conforme')], default='conforme', max_length=20)),
                ('phares_avant', models.CharField(choices=[('ok', 'OK'), ('defectueux', 'Défectueux')], default='ok', max_length=20)),
                ('phares_arriere', models.CharField(choices=[('ok', 'OK'), ('defectueux', 'Défectueux')], default='ok', max_length=20)),
                ('clignotants', models.CharField(choices=[('ok', 'OK'), ('defectueux', 'Défectueux')], default='ok', max_length=20)),
                ('etat_pneus', models.CharField(choices=[('ok', 'OK'), ('usure', 'Usure'), ('critique', 'Critique')], default='ok', max_length=20)),
                ('carrosserie', models.CharField(choices=[('ok', 'OK'), ('rayures', 'Rayures mineures'), ('dommages', 'Dommages importants')], default='ok', max_length=20)),
                ('tableau_bord', models.CharField(choices=[('ok', 'OK'), ('voyants', 'Voyants allumés')], default='ok', max_length=20)),
                ('freins', models.CharField(choices=[('ok', 'OK'), ('usure', 'Usure'), ('defectueux', 'Défectueux')], default='ok', max_length=20)),
                ('ceintures', models.CharField(choices=[('ok', 'OK'), ('defectueuses', 'Défectueuses')], default='ok', max_length=20)),
                ('proprete', models.CharField(choices=[('ok', 'OK'), ('sale', 'Sale')], default='ok', max_length=20)),
                ('carte_grise', models.CharField(choices=[('present', 'Présente'), ('absent', 'Absente')], default='present', max_length=20)),
                ('assurance', models.CharField(choices=[('present', 'Présente'), ('absent', 'Absente')], default='present', max_length=20)),
                ('triangle', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent')], default='present', max_length=20)),
                ('type_check', models.CharField(choices=[('depart', 'Avant course'), ('retour', 'Après course')], default='depart', max_length=10, verbose_name='Type de check-list')),
                ('kilometrage', models.PositiveIntegerField()),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('controleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_lists_effectuees', to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_lists', to='core.vehicule')),
            ],
        ),
    ]
