# Generated by Django 4.2.20 on 2025-06-02 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_applicationcontrol_historiquekilometrage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiviVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('date_immatriculation', models.DateField(blank=True, null=True)),
                ('distance_parcourue', models.PositiveIntegerField(default=0)),
                ('distance_totale', models.PositiveIntegerField(default=0)),
                ('nombre_courses', models.PositiveIntegerField(default=0)),
                ('nombre_entretiens', models.PositiveIntegerField(default=0)),
                ('volume_carburant_consomme', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='core.vehicule')),
            ],
            options={
                'unique_together': {('vehicule', 'date')},
            },
        ),
    ]
