# Generated by Django 4.2.20 on 2025-06-02 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_applicationcontrol_historiquekilometrage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ravitaillement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ravitaillement', models.DateTimeField(auto_now_add=True)),
                ('nom_station', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom de la station')),
                ('kilometrage_avant', models.PositiveIntegerField(default=0)),
                ('kilometrage_apres', models.PositiveIntegerField(default=0)),
                ('litres', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('cout_unitaire', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('cout_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images_ravitaillements/', verbose_name='Photo du reçu')),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ravitaillements_chauffeur', to=settings.AUTH_USER_MODEL)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ravitaillements_crees', to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ravitaillements', to='core.vehicule')),
            ],
        ),
    ]
