# Generated by Django 4.2.20 on 2025-06-22 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_message_is_system_message_alter_message_sender'),
        ('ravitaillement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ravitaillement',
            name='nom_station',
            field=models.CharField(blank=True, help_text="À utiliser uniquement si la station n'est pas dans la liste", max_length=100, null=True, verbose_name='Nom de la station (si non répertoriée)'),
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la station')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code postal')),
                ('pays', models.CharField(default='République Démocratique du Congo', max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('est_active', models.BooleanField(default=True, verbose_name='Active')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='core.etablissement')),
            ],
            options={
                'verbose_name': 'Station de ravitaillement',
                'verbose_name_plural': 'Stations de ravitaillement',
                'ordering': ['nom'],
                'unique_together': {('etablissement', 'nom')},
            },
        ),
        migrations.AddField(
            model_name='ravitaillement',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ravitaillements', to='ravitaillement.station', verbose_name='Station de ravitaillement'),
        ),
    ]
