# Generated by Django 4.2.20 on 2025-06-27 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_message_is_system_message_alter_message_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_info', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntretienNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometrage_actuel', models.PositiveIntegerField()),
                ('kilometrage_prochain', models.PositiveIntegerField(help_text='Kilométrage auquel le prochain entretien est nécessaire')),
                ('is_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretien_notifications', to='core.vehicule')),
            ],
            options={
                'verbose_name': "Notification d'entretien",
                'verbose_name_plural': "Notifications d'entretien",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='DocumentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('carte_grise', 'Carte Grise'), ('assurance', 'Assurance'), ('controle_technique', 'Contrôle Technique'), ('vignette', 'Vignette'), ('stationnement', 'Stationnement')], max_length=50)),
                ('date_expiration', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_notifications', to='core.vehicule')),
            ],
            options={
                'verbose_name': 'Notification de document',
                'verbose_name_plural': 'Notifications de documents',
                'ordering': ['date_expiration'],
            },
        ),
    ]
