# Generated by Django 4.2.20 on 2025-07-07 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushsubscription',
            name='subscription_info',
        ),
        migrations.RemoveField(
            model_name='pushsubscription',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='auth',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='endpoint',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='p256dh',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
